title: MSU Hub

baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'

description: Сообщество студентов и выпускников ВМК МГУ

header:
  title: CMC MSU Hub
  tagline: Сообщество студентов и выпускников ВМК МГУ
  background_img: images/main.png

  has_nav: true
  nav_links:
    - label: Главная
      url: /
      style: link
    - label: Отзывы выпускников
      url: /reviews
      style: link
    - label: Рейтинг кафедр
      url: https://cmc2rise.msut.me
      style: link
    - label: Курс ИИвИИ
      url: /aiinir
      style: link
    - label: Зарплатный опрос
      url: /#salary
      style: link

  has_social: true
  social_links:
    - label: Telegram
      url: 'https://t.me/cs_msu'
      style: icon
      icon_class: fa-telegram
      new_window: true


footer:
  content: '&copy; CMC MSU Hub'

palette: orange

sass:
  indentWidth: 4
  style: nested
  precision: 10

plugins:
  - jekyll-menus

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - readme.md
  - netlify.toml
